### ISSUE TITLE
Changing Profile Priority

### ISSUE THREAD

**Issue by akinuri** [jorgebv/windows-wifi-api#1]
Hi there again :)

Another useful feature would be being able to change the priority (order) of the profiles. I found the corresponding function for the native wifi [WlanSetProfilePosition ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms706810%28v=vs.85%29.aspx), but I wish I could read C++. Don't know how to implement it in C#.

As a side note, in the tool I'm creating, only this priority ordering thing is missing.

![capture](https://cloud.githubusercontent.com/assets/13146977/8476843/f54f9dfc-20cd-11e5-8a7f-4fdc2b546573.PNG)

"Add" will pop up a new form to fill manually, "Remove" deletes a profile, "Up" and "Down" changes the priority, and "Import" and "Export" handles XMLs. It's working fine so far (except up and down), but I'm not sure if the code I'm using is the most efficient one. I might be using redundant code, so I'm thinking about opening other issues for them. For example, for "DeleteProfile" and "SetProfile" methods. Hope that's okay. Future viewers can benefit from the examples since there isn't a documentation.

**Comment by jovergar** [comment]
I'll see if I can get this added, maybe today or tomorrow. Feel free to open any issues you wish, I'll work on adding documentation/examples slowly.

**Comment by jorgebv** [comment]
I'll see if I can get this added, maybe today or tomorrow. Feel free to open any issues you wish, I'll work on adding documentation/examples slowly.

**Comment by jorgebv** [comment]
Added this function with this commit: https://github.com/jorgebv/windows-wifi-api/commit/864cc437dfbeca5504b491722dd74a60f173a6ae
