### ISSUE TITLE
Disconnect function

### ISSUE THREAD

**Issue by DircoDT** [jorgebv/windows-wifi-api#5]
I noticed that there is a function for it in the native DLL that is not exposed by the wrapper API.

In Interop.cs, add:

```
[DllImport("wlanapi.dll")]
public static extern int WlanDisconnect(
    [In] IntPtr clientHandle,
    [In, MarshalAs(UnmanagedType.LPStruct)] Guid interfaceGuid,
    IntPtr pReserved);
```

In WlanApi.cs, add:

```
public void Disconnect()
{
    Wlan.ThrowIfError(
        Wlan.WlanDisconnect(client.clientHandle, info.interfaceGuid, IntPtr.Zero));
}
```

Could also make a synchronous version, like DisconnectSynchronously()...

**Comment by jorgebv** [comment]
I'll add this soon, thank you. I know there are some other things missing as well, but I haven't done a full audit of the headers. My plan was to add functions as the need arose.

**Comment by jorgebv** [comment]
I added a DisconnectAsync function in 854d0f51d481ae6a34e472da193984ae6ee8eb76. I know this is inconsistent with ConnectSynchronously; I will address that separately (I will add a ConnectAsync function).
